//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 MemberComponentTemplate==生物组件项
        ///Parameter==单个参数项
        ///ParameterSet==多个参数项
        ///EntityTemplate==实体项
        ///ComponentTemplate==组件模板项
        ///
        ///AccelerationFactor==加速因子，用于摩擦，冰块这种，比较原版玩家女性的因子高点，所以跑的快，可能用于冰面，其它的没试过有待测试
        ///ActiveSlotIndex==激活的格子位置
        ///AdjustableDelayGateBlockBehavior==延迟门行为
        ///AICreature==生物的基本功能。就是生物需要的基本属性、掉落物品，给各种动物的父类继承，快速编辑AI
        ///AimingSights==瞄准，玩家的瞄准行为，就是射箭、丢石头这种
        ///Air==空气
        ///AirCapacity==氧气容量
        ///AirDrag==空气阻力
        ///AllowManualWakeUp==
        ///Alpaca==羊驼父系，老k旧案
        ///Alpaca_Shorn==被修剪后的羊驼，老k旧案
        ///Alpaca_White==白色羊驼，老k旧案
        ///AlwaysEnabled==始终自动跳跃        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DatabaseWordsDescription {
            get {
                return ResourceManager.GetString("DatabaseWordsDescription", resourceCulture);
            }
        }
    }
}
